# Generated by Django 5.0.4 on 2024-05-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='films',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AddField(
            model_name='films',
            name='image_url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='films',
            name='image',
            field=models.ImageField(upload_to='poster/static/poster/img/', verbose_name='Постер'),
        ),
    ]
